export const ModelFieldTypes = [
  'bigint',
  'binary',
  'bit',
  'blob',
  'char',
  'date',
  'datetime',
  'decimal',
  'double',
  'enum',
  'float',
  'geomotry',
  'geomotrycollect',
  'geomotrycollect',
  'int',
  'integer',
  'json',
  'longblob',
  'longtext',
  'mediumblob',
  'mediumint',
  'mediumtext',
  'numeric',
  'point',
  'polygon',
  'real',
  'set',
  'text',
  'time',
  'timestamp',
  'tinyblob',
  'tinytext',
  'tinyint',
  'varbinary',
  'varchar',
  'year',
]

const logicTypeOptions = [
  {
    label: '等于',
    value: 'EQ',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '不等于',
    value: 'NEQ',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '小于',
    value: 'LT',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '小于等于',
    value: 'LTE',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '大于',
    value: 'GT',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '大于等于',
    value: 'GTE',
    help: '当逻辑类型为EQ/NEQ/LT/LTE/GT/GTE时，内容为$param，值为字符类型的数字或时间',
  },
  {
    label: '相间',
    value: 'BETWEEN',
    help: '当逻辑类型为BETWEEN时，内容为$param1,$param2，值为字符类型的数字或时间',
  },
  {
    label: '表达式',
    value: 'EXPR',
    help: '当逻辑类型为EXPR/SCRIPT时，内容为$text，值为字符类型的表达式或脚本',
  },
  {
    label: '脚本',
    value: 'SCRIPT',
    help: '当逻辑类型为EXPR/SCRIPT时，内容为$text，值为字符类型的表达式或脚本',
  },
  {
    label: '并且',
    value: 'AND',
    help: '当逻辑类型为AND时，内容为$key,$key...，值为字符类型的其它表达式定义的key值',
  },
  {
    label: '或',
    value: 'OR',
    help: '当逻辑类型为OR时，内容为$key,$key...，值为字符类型的其它表达式定义的key值',
  },
]
const paramTypeOptions = [
  { label: '字符', value: 'STRING' },
  { label: '数字', value: 'NUMBER' },
  { label: 'JSON', value: 'JSON' },
  { label: '字符数组', value: 'STRING_ARRAY' },
  { label: '数字数组', value: 'NUMBER_ARRAY' },
  { label: '自定义', value: 'CUSTOM' },
]
